import type { ClauseDefinition } from '../../../types/leaseBuilder';

/**
 * Alterations & Improvements — Comprehensive alterations article for Minnesota commercial leases.
 * sortOrder: 435
 */
export const commercialAlterationsClauses: ClauseDefinition[] = [
  // ──────────────────────────────────────────────────────────────────────────
  // ALTERATIONS & IMPROVEMENTS
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'comm-alterations',
    leaseClass: 'commercial',
    category: 'tenant_improvements',
    title: 'Alterations & Improvements',
    description:
      'Governs Tenant\'s right to make alterations and improvements to the Premises, including consent requirements, construction standards, mechanics lien obligations, and ownership and removal of improvements at lease expiration.',
    htmlContent: `<h3>Alterations &amp; Improvements</h3>
<p><strong>Landlord Consent Required.</strong> Except as provided below for Permitted Alterations, Tenant shall not make, or cause or permit to be made, any alterations, additions, or improvements to the Premises (collectively, &ldquo;Alterations&rdquo;) without the prior written consent of Landlord, which consent shall not be unreasonably withheld, conditioned, or delayed for non-structural, interior-only Alterations that do not affect the Building&rsquo;s mechanical, electrical, plumbing, HVAC, or life-safety systems. Alterations that are structural in nature, that affect the exterior of the Building, or that affect the Building&rsquo;s mechanical, electrical, plumbing, HVAC, or life-safety systems shall require Landlord&rsquo;s prior written consent, which Landlord may withhold in its sole and absolute discretion.</p>
<p>Tenant&rsquo;s request for Landlord&rsquo;s consent shall be accompanied by detailed plans and specifications prepared by a licensed architect or engineer (as applicable), a list of proposed contractors, and such other information as Landlord may reasonably request. Landlord shall respond to any such request within twenty (20) business days after receipt of all required documentation; failure to respond within such period shall not be deemed approval.</p>
<p><strong>Permitted Alterations.</strong> Notwithstanding the foregoing, Tenant may make minor, non-structural, interior-only Alterations to the Premises without Landlord&rsquo;s prior written consent, provided that: (a) the total cost of any single project or series of related projects does not exceed Five Thousand Dollars ($5,000); (b) Tenant provides Landlord with at least ten (10) days&rsquo; prior written notice describing the proposed work; (c) the work does not affect the Building&rsquo;s mechanical, electrical, plumbing, HVAC, structural, or life-safety systems; (d) the work does not affect the exterior of the Building; and (e) the work complies with all applicable laws and the terms of this Lease (each, a &ldquo;Permitted Alteration&rdquo;).</p>
<p><strong>Construction Standards.</strong> All Alterations (including Permitted Alterations) shall be: (a) performed in a good and workmanlike manner, using new materials of quality equal to or better than the existing improvements in the Premises; (b) performed only by licensed, bonded, and insured contractors and subcontractors approved by Landlord in advance (such approval not to be unreasonably withheld); (c) performed in compliance with all applicable federal, state, and local laws, codes, regulations, and the requirements of all governmental authorities having jurisdiction; (d) performed in a manner that does not unreasonably interfere with the use and enjoyment of the Building by other tenants; and (e) completed free and clear of all mechanics&rsquo; liens, materialmen&rsquo;s liens, and other encumbrances.</p>
<p><strong>Mechanics&rsquo; Liens.</strong> Tenant shall pay all costs for any Alterations performed by or on behalf of Tenant and shall not permit any mechanics&rsquo; lien or materialmen&rsquo;s lien to be filed against the Premises, the Building, or Landlord&rsquo;s interest therein arising from work performed or materials furnished at the request of Tenant. If any such lien is filed, Tenant shall cause it to be released of record (by payment, bonding, or otherwise) within thirty (30) days after Tenant receives notice of such filing. If Tenant fails to cause such lien to be released within such thirty (30) day period, Landlord may take any action Landlord deems necessary to release such lien, and Tenant shall reimburse Landlord for all costs so incurred, plus a ten percent (10%) administrative fee, within ten (10) business days after receipt of Landlord&rsquo;s invoice. Landlord shall have the right, at any time, to post and maintain on the Premises and record in the public records such notices of non-responsibility as Landlord deems necessary to protect Landlord&rsquo;s interest from mechanics&rsquo; and materialmen&rsquo;s liens.</p>
<p><strong>Ownership and Removal of Alterations.</strong> Unless Landlord otherwise agrees in writing at the time of granting consent, all Alterations made to the Premises shall, upon expiration or earlier termination of this Lease, become the property of Landlord and shall remain upon and be surrendered with the Premises; provided, however, that Landlord may, at Landlord&rsquo;s election, require Tenant to remove any or all non-standard Alterations and to restore the Premises to their prior condition at Tenant&rsquo;s sole cost and expense. Landlord shall notify Tenant of any required removal at the time Landlord grants consent for the Alteration, or, if no consent was required, within thirty (30) days after Landlord receives Tenant&rsquo;s written notice of the Permitted Alteration. Landlord&rsquo;s failure to notify Tenant of required removal within the applicable period shall be deemed a waiver of Landlord&rsquo;s removal rights with respect to that specific Alteration.</p>
<p><strong>Trade Fixtures.</strong> Notwithstanding the above, all trade fixtures, equipment, and personal property installed by Tenant at Tenant&rsquo;s expense that are not permanently affixed to the Premises and that can be removed without material damage to the Premises shall remain the property of Tenant and shall be removed by Tenant on or before the expiration or earlier termination of this Lease. Tenant shall promptly repair any damage caused by the removal of Tenant&rsquo;s trade fixtures and personal property. Any trade fixtures or personal property not removed by Tenant by the expiration or earlier termination of this Lease shall, at Landlord&rsquo;s election, be deemed abandoned and shall become the property of Landlord, or Landlord may remove and store or dispose of such items at Tenant&rsquo;s sole cost and expense.</p>`,
    isRequired: true,
    placeholders: [],
    sortOrder: 435,
    version: '1.0.0',
    lastReviewedDate: '2026-04-22',
  },
];
