/**
 * Minnesota State-Level Commercial Validation Rules
 */

import type { ValidationRule } from '../../../types/leaseBuilder';

export const commercialStateRules: ValidationRule[] = [
  {
    id: 'comm-rent-positive',
    leaseClass: 'commercial',
    description: 'Base rent must be greater than zero',
    severity: 'error',
    field: 'commercial.financial.baseRentMonthly',
    condition: { type: 'min_value', value: 1 },
    message: 'Base monthly rent must be greater than $0.',
    appliesTo: 'state',
  },
  {
    id: 'comm-dates-valid',
    leaseClass: 'commercial',
    description: 'End date required for fixed-term leases',
    severity: 'error',
    field: 'commercial.leaseStructure.endDate',
    condition: {
      type: 'required_if',
      dependsOnField: 'leaseType',
      dependsOnValue: 'fixed_term',
    },
    message: 'End date is required for fixed-term commercial leases.',
    appliesTo: 'state',
  },
  {
    id: 'comm-escalation-conflict',
    leaseClass: 'commercial',
    description: 'Escalation type must be valid and consistent',
    severity: 'error',
    field: 'commercial.financial.escalationType',
    condition: { type: 'custom', customFn: 'escalationConflict' },
    message: 'Escalation configuration is incomplete. If step schedule is selected, at least one rent step must be defined.',
    helpText: 'Only one escalation type can be active. If you selected Step Schedule, provide at least one year-by-year rent entry.',
    appliesTo: 'state',
  },
  {
    id: 'comm-cam-gross-conflict',
    leaseClass: 'commercial',
    description: 'Cannot enable CAM charges with a Gross lease structure',
    severity: 'error',
    field: 'commercial.financial.camEnabled',
    condition: { type: 'custom', customFn: 'camGrossConflict' },
    message: 'CAM (Common Area Maintenance) charges cannot be enabled with a Gross lease. Gross leases include all operating costs in base rent.',
    helpText: 'A Gross lease means the landlord covers all operating expenses (taxes, insurance, maintenance) within the base rent. If you want to pass through expenses, select NNN (Triple Net) or Modified Gross lease type.',
    appliesTo: 'state',
  },
  {
    id: 'comm-cure-period-monetary',
    leaseClass: 'commercial',
    description: 'Monetary default cure period must be defined',
    severity: 'error',
    field: 'commercial.risk.monetaryDefaultCureDays',
    condition: { type: 'min_value', value: 1 },
    message: 'A monetary default cure period (in days) must be specified.',
    helpText: 'This is the number of days a tenant has to cure a payment default after receiving notice. Common values are 5-10 business days.',
    appliesTo: 'state',
  },
  {
    id: 'comm-cure-period-nonmonetary',
    leaseClass: 'commercial',
    description: 'Non-monetary default cure period must be defined',
    severity: 'error',
    field: 'commercial.risk.nonMonetaryDefaultCureDays',
    condition: { type: 'min_value', value: 1 },
    message: 'A non-monetary default cure period (in days) must be specified.',
    helpText: 'This is the number of days a tenant has to cure a non-payment default (e.g., breach of use restrictions) after receiving notice. Common values are 15-30 days.',
    appliesTo: 'state',
  },
  {
    id: 'comm-environmental-required',
    leaseClass: 'commercial',
    description: 'Environmental compliance clause cannot be removed',
    severity: 'error',
    field: 'commercial.operations.environmentalComplianceIncluded',
    condition: { type: 'custom', customFn: 'environmentalRequired' },
    message: 'The environmental compliance clause is required and cannot be removed from commercial leases.',
    helpText: 'Environmental compliance and hazardous materials indemnification is a standard and essential component of commercial leases to protect both landlord and tenant from environmental liability.',
    appliesTo: 'state',
  },
  {
    id: 'comm-insurance-gl-required',
    leaseClass: 'commercial',
    description: 'General liability insurance amount must be specified',
    severity: 'error',
    field: 'commercial.operations.insuranceGLAmount',
    condition: { type: 'min_value', value: 1 },
    message: 'A commercial general liability (CGL) insurance amount per occurrence is required.',
    appliesTo: 'state',
  },
  {
    id: 'comm-property-required',
    leaseClass: 'commercial',
    description: 'Property must be selected',
    severity: 'error',
    field: 'propertyId',
    condition: { type: 'required' },
    message: 'A property must be selected.',
    appliesTo: 'state',
  },
  {
    id: 'comm-tenant-required',
    leaseClass: 'commercial',
    description: 'At least one tenant must be selected',
    severity: 'error',
    field: 'tenantIds',
    condition: { type: 'required' },
    message: 'At least one tenant must be selected.',
    appliesTo: 'state',
  },
  {
    id: 'comm-permitted-use-required',
    leaseClass: 'commercial',
    description: 'Permitted use description is required',
    severity: 'error',
    field: 'commercial.useAndBuildout.permittedUse',
    condition: { type: 'required' },
    message: 'A description of the permitted use of the premises is required.',
    appliesTo: 'state',
  },
  // === WARNINGS ===
  {
    id: 'comm-startup-guarantee',
    leaseClass: 'commercial',
    description: 'Recommend personal guarantee for startup tenants',
    severity: 'warning',
    field: 'commercial.risk.personalGuaranteeRequired',
    condition: { type: 'required' },
    message: 'Personal guarantees are typically recommended for startup or newly formed tenant entities to reduce landlord risk.',
    helpText: 'If the tenant entity was formed less than 2 years ago or has limited operating history, a personal guarantee from an individual principal provides additional security for the landlord.',
    appliesTo: 'state',
  },
  {
    id: 'comm-low-gl-coverage',
    leaseClass: 'commercial',
    description: 'General liability coverage below recommended minimum',
    severity: 'warning',
    field: 'commercial.operations.insuranceGLAmount',
    condition: { type: 'min_value', value: 1000000 },
    message: 'General liability coverage is below the recommended minimum of $1,000,000 per occurrence.',
    helpText: 'Industry standard for commercial general liability insurance is typically $1,000,000 per occurrence. Lower limits may leave the landlord exposed to inadequate coverage.',
    appliesTo: 'state',
  },
  {
    id: 'comm-high-default-interest',
    leaseClass: 'commercial',
    description: 'Default interest rate is unusually high',
    severity: 'warning',
    field: 'commercial.financial.defaultInterestRate',
    condition: { type: 'max_value', value: 18 },
    message: 'The default interest rate exceeds 18% per annum, which may be considered excessive.',
    helpText: 'While Minnesota does not have a statutory cap on commercial default interest rates, rates above 18% may be challenged as unconscionable in court.',
    appliesTo: 'state',
  },
  {
    id: 'comm-no-cam-audit',
    leaseClass: 'commercial',
    description: 'No CAM audit rights provided to tenant',
    severity: 'warning',
    field: 'commercial.financial.camAuditRights',
    condition: { type: 'required' },
    message: 'CAM audit rights have not been provided to the tenant. This is a common tenant negotiation point.',
    helpText: 'Providing tenants with the right to audit CAM reconciliation statements is standard commercial practice and builds trust. Consider enabling audit rights.',
    appliesTo: 'state',
  },
  {
    id: 'comm-sole-discretion-assignment',
    leaseClass: 'commercial',
    description: 'Assignment at sole discretion may be challenged',
    severity: 'warning',
    field: 'commercial.risk.assignmentConsentStandard',
    condition: { type: 'max_value', value: 0 }, // This will use custom logic
    message: 'Assignment consent at landlord\'s sole discretion may be challenged as unreasonable in some jurisdictions.',
    helpText: 'While permitted in Minnesota commercial leases, "sole discretion" consent standards for assignment may face scrutiny. "Not unreasonably withheld" is a more balanced standard.',
    appliesTo: 'state',
  },
];
