/**
 * Minnesota State-Level Residential Validation Rules
 */

import type { ValidationRule } from '../../../types/leaseBuilder';

export const residentialStateRules: ValidationRule[] = [
  {
    id: 'mn-res-rent-positive',
    leaseClass: 'residential',
    description: 'Monthly rent must be greater than zero',
    severity: 'error',
    field: 'residential.rent.monthlyRent',
    condition: { type: 'min_value', value: 1 },
    message: 'Monthly rent must be greater than $0.',
    appliesTo: 'state',
  },
  {
    id: 'mn-res-dates-valid',
    leaseClass: 'residential',
    description: 'End date must be after start date for fixed-term leases',
    severity: 'error',
    field: 'residential.rent.endDate',
    condition: {
      type: 'required_if',
      dependsOnField: 'leaseType',
      dependsOnValue: 'fixed_term',
    },
    message: 'End date is required for fixed-term leases and must be after the start date.',
    appliesTo: 'state',
  },
  {
    id: 'mn-res-due-day-range',
    leaseClass: 'residential',
    description: 'Due day must be between 1 and 28',
    severity: 'error',
    field: 'residential.rent.dueDay',
    condition: { type: 'max_value', value: 28 },
    message: 'Rent due day must be between 1 and 28.',
    appliesTo: 'state',
  },
  {
    id: 'mn-res-late-fee-max-8pct',
    leaseClass: 'residential',
    description: 'Late fee percentage cannot exceed 8% of monthly rent under MN law',
    severity: 'error',
    field: 'residential.rent.lateFeeAmount',
    condition: { type: 'custom', customFn: 'lateFeePercentageExceedsMax' },
    message: 'Late fee percentage cannot exceed 8% of monthly rent under Minnesota Statute 504B.177.',
    helpText: 'Minnesota law limits late fees to no more than 8% of the overdue rent payment. If you selected a percentage-based late fee, the percentage must be 8% or less.',
    appliesTo: 'state',
  },
  {
    id: 'mn-res-deposit-return-21days',
    leaseClass: 'residential',
    description: 'Security deposit must be returned within 21 days',
    severity: 'error',
    field: 'residential.deposit.securityDeposit',
    condition: { type: 'required' },
    message: 'Security deposit amount is required. Minnesota law requires return within 21 days with itemized deductions.',
    helpText: 'Under MN Stat. 504B.178, the landlord must return the security deposit (with interest if required) within 21 days of lease termination and tenant move-out, along with an itemized statement of any deductions.',
    appliesTo: 'state',
  },
  {
    id: 'mn-res-lead-paint-pre1978',
    leaseClass: 'residential',
    description: 'Lead-based paint disclosure required for pre-1978 properties',
    severity: 'error',
    field: 'triggeredDisclosures',
    condition: { type: 'custom', customFn: 'requiresLeadPaintDisclosure' },
    message: 'Lead-based paint disclosure is required for properties built before 1978.',
    helpText: 'Federal law (42 U.S.C. 4852d) requires landlords of pre-1978 housing to disclose known lead-based paint hazards and provide the EPA pamphlet "Protect Your Family From Lead in Your Home."',
    appliesTo: 'state',
  },
  {
    id: 'mn-res-bed-bug-disclosure',
    leaseClass: 'residential',
    description: 'Bed bug disclosure is always required under MN law',
    severity: 'error',
    field: 'triggeredDisclosures',
    condition: { type: 'required' },
    message: 'Bed bug disclosure must be included in every Minnesota residential lease.',
    helpText: 'Minnesota Statute 504B.161 requires landlords to disclose known bed bug infestations to prospective tenants before a lease is signed.',
    appliesTo: 'state',
  },
  {
    id: 'mn-res-dv-notice',
    leaseClass: 'residential',
    description: 'Domestic violence early termination notice is always required',
    severity: 'error',
    field: 'triggeredDisclosures',
    condition: { type: 'required' },
    message: 'Domestic violence early termination rights notice must be included.',
    helpText: 'Minnesota Statute 504B.206 provides tenants who are victims of domestic violence, sexual assault, or stalking the right to terminate their lease early with proper documentation.',
    appliesTo: 'state',
  },
  {
    id: 'mn-res-grace-period-min',
    leaseClass: 'residential',
    description: 'Recommend minimum grace period of 1 day',
    severity: 'warning',
    field: 'residential.rent.gracePeriodDays',
    condition: { type: 'min_value', value: 1 },
    message: 'A grace period of at least 1 day is recommended before assessing late fees.',
    helpText: 'While not strictly required by state law, providing a reasonable grace period is considered best practice and may be required by local ordinance.',
    appliesTo: 'state',
  },
  {
    id: 'mn-res-payment-methods-required',
    leaseClass: 'residential',
    description: 'At least one payment method must be specified',
    severity: 'error',
    field: 'residential.rent.paymentMethods',
    condition: { type: 'required' },
    message: 'At least one accepted payment method must be specified.',
    appliesTo: 'state',
  },
  {
    id: 'mn-res-property-required',
    leaseClass: 'residential',
    description: 'Property must be selected',
    severity: 'error',
    field: 'propertyId',
    condition: { type: 'required' },
    message: 'A property must be selected.',
    appliesTo: 'state',
  },
  {
    id: 'mn-res-unit-required',
    leaseClass: 'residential',
    description: 'Unit must be selected',
    severity: 'error',
    field: 'unitId',
    condition: { type: 'required' },
    message: 'A unit must be selected.',
    appliesTo: 'state',
  },
  {
    id: 'mn-res-tenant-required',
    leaseClass: 'residential',
    description: 'At least one tenant must be selected',
    severity: 'error',
    field: 'tenantIds',
    condition: { type: 'required' },
    message: 'At least one tenant must be selected.',
    appliesTo: 'state',
  },
];
